apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: {{ template "helm-guestbook.fullname" . }}
    {{- if .Values.rollout }}
    - apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      name: {{ template "helm-guestbook.fullname" . }}
    {{- else }}
    - apiVersion: apps/v1
      kind: ReplicaSet
      labelSelector:
        matchLabels:
          app: {{ template "helm-guestbook.name" . }}
          release: {{ .Release.Name }}
    {{- end }}
  placement:
    clusterAffinity:
      clusterNames:
        - k8s1
        - karmada
    replicaScheduling:
      {{- if .Values.SchedulingType }}
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - k8s1
          weight: 100
        - targetCluster:
            clusterNames:
            - karmada
          weight: {{ .Values.karmadaWeight }}
      {{- else }}
      replicaSchedulingType: Duplicated
      {{- end }}
